<!DOCTYPE html>
    <html>
    <head>
      <meta charset='utf-8'>
      <meta name='viewport' content='width=device-width'>
      <title>Politicas de Privacidad</title>
      <style> body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding:1em; } </style>
    </head> 
    <body>
    <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Política de privacidad</font></font></h2> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">[Nombre del desarrollador / empresa] creó la aplicación [Nombre de la aplicación] como [aplicación de código abierto / free / freemium / ad-support / commercial]. </font><font style="vertical-align: inherit;">Este SERVICIO es provisto por [Nombre del Desarrollador / Compañía] [sin costo] y está diseñado para ser utilizado tal como está.
                  </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Esta página se utiliza para informar a los visitantes con respecto a [mi / nuestras] políticas con la recopilación, el uso y la divulgación de información personal si alguien decide utilizar el Servicio [mi / nuestro].
                  </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Si elige utilizar el servicio [mi / nuestro], entonces acepta la recopilación y el uso de la información relacionada con esta política. </font><font style="vertical-align: inherit;">La información personal que [I / We] recopilamos se utiliza para proporcionar y mejorar el servicio. </font><font style="vertical-align: inherit;">[I / We] no usaremos ni compartiremos su información con nadie, excepto como se describe en esta Política de privacidad.
                  </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Los términos utilizados en esta Política de privacidad tienen los mismos significados que en nuestros Términos y condiciones, a los que se puede acceder en [Nombre de la aplicación] a menos que se defina lo contrario en esta Política de privacidad.
                  </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Recopilación y uso de información</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para una mejor experiencia, mientras usa nuestro Servicio, es posible que [I / We] le solicite que nos proporcione cierta información de identificación personal [agregue cualquier otra cosa que recopile aquí, por ejemplo, nombre de los usuarios, dirección, ubicación, imágenes] La información que [I / La solicitud de] será [retenida en su dispositivo y no será recopilada por [me / us] de ninguna manera] / [retenida por nosotros y utilizada como se describe en esta política de privacidad].
                  </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">La aplicación utiliza servicios de terceros que pueden recopilar información utilizada para identificarlo.</font></font></p> <div><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Enlace a la política de privacidad de los proveedores de servicios de terceros utilizados por la aplicación</font></font></p> <ul><li><a href="https://www.google.com/policies/privacy/" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Servicios de Google Play</font></font></a></li><!----><!----><!----><!----><!----><!----><!----></ul></div> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Dato de registro</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">[I / We] quiero informarle que cada vez que utilice [mi / nuestro] Servicio, en caso de un error en la aplicación [I / We] recopilamos datos e información (a través de productos de terceros) en su teléfono llamado Log Data . </font><font style="vertical-align: inherit;">Estos datos de registro pueden incluir información como la dirección del Protocolo de Internet ("IP") de su dispositivo, el nombre del dispositivo, la versión del sistema operativo, la configuración de la aplicación cuando utiliza el Servicio [mi / nuestro], la fecha y hora de uso del Servicio. , y otras estadísticas.
                  </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Galletas</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Las cookies son archivos con una pequeña cantidad de datos que se utilizan comúnmente como identificadores únicos anónimos. </font><font style="vertical-align: inherit;">Estos se envían a su navegador desde los sitios web que visita y se almacenan en la memoria interna de su dispositivo.
                  </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Este Servicio no utiliza estas "cookies" explícitamente. </font><font style="vertical-align: inherit;">Sin embargo, la aplicación puede usar códigos de terceros y bibliotecas que usan "cookies" para recopilar información y mejorar sus servicios. </font><font style="vertical-align: inherit;">Tiene la opción de aceptar o rechazar estas cookies y saber cuándo se envía una cookie a su dispositivo. </font><font style="vertical-align: inherit;">Si decide rechazar nuestras cookies, es posible que no pueda utilizar algunas partes de este Servicio.
                  </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Proveedores de servicio</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> [I / We] puede contratar a terceros y personas físicas por los siguientes motivos:</font></font></p> <ul><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para facilitar nuestro Servicio;</font></font></li> <li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para proporcionar el Servicio en nuestro nombre;</font></font></li> <li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para realizar servicios relacionados con el servicio; </font><font style="vertical-align: inherit;">o</font></font></li> <li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para ayudarnos a analizar cómo se utiliza nuestro servicio.</font></font></li></ul> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">[I / We] queremos informar a los usuarios de este Servicio que estos terceros tienen acceso a su Información personal. </font><font style="vertical-align: inherit;">El motivo es realizar las tareas asignadas a ellos en nuestro nombre. </font><font style="vertical-align: inherit;">Sin embargo, están obligados a no divulgar o utilizar la información para ningún otro propósito.
                  </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Seguridad</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">[I / We] valoramos su confianza al proporcionarnos su información personal, por lo que nos esforzamos por utilizar medios comercialmente aceptables para protegerla. </font><font style="vertical-align: inherit;">Pero recuerde que ningún método de transmisión a través de Internet, o método de almacenamiento electrónico es 100% seguro y confiable, y [I / We] no puede garantizar su seguridad absoluta.
                  </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Enlaces a otros sitios</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Este servicio puede contener enlaces a otros sitios. </font><font style="vertical-align: inherit;">Si hace clic en un enlace de terceros, se le dirigirá a ese sitio. </font><font style="vertical-align: inherit;">Tenga en cuenta que estos sitios externos no son operados por [me / us]. </font><font style="vertical-align: inherit;">Por lo tanto, [I / We] le recomendamos encarecidamente que revise la Política de privacidad de estos sitios web. </font><font style="vertical-align: inherit;">[I / We] no tenemos control ni asumimos ninguna responsabilidad por el contenido, las políticas de privacidad o las prácticas de los sitios o servicios de terceros.
                  </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Privacidad de los niños</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Estos Servicios no se dirigen a personas menores de 13 años. [Yo / Nosotros] no recopilamos a sabiendas información de identificación personal de niños menores de 13 años. En el caso [Yo / Nosotros] descubrimos que un niño menor de 13 años nos ha proporcionado [yo / nosotros] con información personal, [I / We] lo eliminamos inmediatamente de nuestros servidores. </font><font style="vertical-align: inherit;">Si usted es padre o tutor y sabe que su hijo nos ha proporcionado información personal, comuníquese con [me / us] para que [I / We] podamos hacer las acciones necesarias.
                  </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cambios a esta política de privacidad</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">[Yo / Nosotros] podemos actualizar nuestra Política de Privacidad de vez en cuando. </font><font style="vertical-align: inherit;">Por lo tanto, se recomienda revisar esta página periódicamente para ver si hay cambios. </font><font style="vertical-align: inherit;">[I / We] le notificaremos cualquier cambio mediante la publicación de la nueva Política de privacidad en esta página. </font><font style="vertical-align: inherit;">Estos cambios entrarán en vigencia inmediatamente después de su publicación en esta página.
                  </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Contáctenos</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Si tiene alguna pregunta o sugerencia acerca de [mi / nuestra] Política de privacidad, no dude en ponerse en contacto con [yo / nosotros].
                  </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Esta página de política de privacidad se creó en </font></font><a href="https://privacypolicytemplate.net" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">privacypolicytemplate.net</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> 
                    y fue modificada / generada por el generador de </font></font><a href="https://app-privacy-policy-generator.firebaseapp.com/" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">políticas de privacidad de la aplicación</font></font></a></p>
    </body>
    </html>
      